FROM alpine

RUN apk update && apk upgrade && apk add vim
ENTRYPOINT vim
# 
# docker build -t build00 .

# docker run --name ex00 -ti --rm build00
#-i pour comuniquer avec
#-t pour utiliser ctrl c par exemple
